server:
  port: 3000
  servlet:
    context-path: /demo
spring:
  datasource:
    hikari:
      username: springbootdemo
      password: '{springbootdemo!@#123}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.0.7:3306/springbootdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 172.16.0.5
    port: 6379
    # Connect timeout time (remember to add units，Duration）
    timeout: 10000ms
    # Redis There are 16 shards by default.
    # database: 0
    lettuce:
      pool:
        # The maximum number of connections of the connection pool (the negative value indicates that there is no limit) default 8
        max-active: 8
        #The maximum blocking time of the connection pool (the negative value indicates that there is no limit) default -1
        max-wait: -1ms
        # The maximum free connection in the connection pool default 8
        max-idle: 8
        #The smallest idle connection in the connection pool default 0
        min-idle: 0
jwt:
  config:
    key: xkcoding
    ttl: 600000
    remember: 604800000
logging:
  level:
    com.xkcoding.rbac.security: debug
custom:
  config:
    ignores:
      # Required poask 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # Request to be filtered，Unlimited method
      pattern:
        - "/test/*"